import { ReduxProvider } from "@/redux/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

//import { Header } from 'cegov-antd'
import { Typography, Divider, Switch } from "antd";
import { CheckOutlined, CloseOutlined } from "@ant-design/icons";
const { Title, Paragraph } = Typography;

//import { Providers } from "./GlobalRedux/provider";
import "./globals.css";

//import { useAppAccessibility } from './context/accessibilityContext'
import { useAppAccessibility } from "@/context/acessibilityContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const { lengthText } = useAppAccessibility()
  return (
    <html lang="en">
      <body className={inter.className} >
      
        <ReduxProvider >
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
